[supervisord]

[fcgi-program:sights-v2]
directory=/opt/sights-v2/server/
socket=tcp://localhost:8000
command=/opt/sights-v2/server/.venv/bin/uvicorn --fd 0 server:app --workers 1 --host 0.0.0.0
numprocs=4
process_name=uvicorn-%(process_num)d
stdout_logfile=/var/log/supervisor/uvicorn.out.log
stderr_logfile=/var/log/supervisor/uvicorn.err.log
stdout_maxbytes=1MB
stderr_maxbytes=1MB
